import { PageData } from "../types"

export const CONNECTIVE: PageData[] = [
    {
        type: "directory",
        id: "connective_tissue",
        image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/dc/Hist.Technik_%282%29.jpg/960px-Hist.Technik_%282%29.jpg?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
        title: "Connective Tissue",
        children: [
            "mesenchyme",
            "mucous_connective_tissue",
            "areolar_connective_tissue",
            "adipose_tissue",
            "reticular_connective_tissue",
            "dense_regular_connective_tissue",
            "dense_irregular_connective_tissue",
            "elastic_connective_tissue",
            "hyaline_cartilage",
            "fibrocartilage",
            "elastic_cartilage",
            "compact_bone",
            "spongy_bone",
            "blood",
            "lymph",
        ],
    },
    {
        type: "detail",
        id: "mesenchyme",
        title: "Mesenchyme",
        image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f8/Mesenchyme.JPG/500px-Mesenchyme.JPG?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
    },
    {
        type: "detail",
        id: "mucous_connective_tissue",
        title: "Mucous (mucoid) connective tissue",
        image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/52/MSC_high_magnification.jpg/500px-MSC_high_magnification.jpg?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
    },
    {
        type: "detail",
        id: "areolar_connective_tissue",
        title: "Areolar Connective Tissue",
        image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b4/Normal_Epidermis_and_Dermis_with_Intradermal_Nevus_10x.JPG/960px-Normal_Epidermis_and_Dermis_with_Intradermal_Nevus_10x.JPG?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
    },
    {
        type: "detail",
        id: "adipose_tissue",
        title: "Adipose Tissue",
        image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/65/Blausen_0012_AdiposeTissue.png/500px-Blausen_0012_AdiposeTissue.png?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
    },
    {
        type: "detail",
        id: "reticular_connective_tissue",
        title: "Reticular Connective Tissue",
        image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/ab/Connective_Tissue_Reticular_%2840885193495%29.jpg/500px-Connective_Tissue_Reticular_%2840885193495%29.jpg?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
    },
    {
        type: "detail",
        id: "dense_regular_connective_tissue",
        title: "Dense Regular Connective Tissue",
        image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a3/Tendon_-_add_-_high_mag.jpg/960px-Tendon_-_add_-_high_mag.jpg?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
    },
    {
        type: "detail",
        id: "dense_irregular_connective_tissue",
        title: "Dense Irregular Connective Tissue",
        image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/13/Blausen_0296_DenseIrregularCT.png/500px-Blausen_0296_DenseIrregularCT.png?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
    },
    {
        type: "detail",
        id: "elastic_connective_tissue",
        title: "Elastic Connective Tissue",
        image: "https://upload.wikimedia.org/wikipedia/commons/c/cb/Gray377.png?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail_unscaled",
    },
    {
        type: "detail",
        id: "hyaline_cartilage",
        title: "Hyaline Cartilage",
        image: "https://upload.wikimedia.org/wikipedia/commons/e/ee/Hypertrophic_Zone_of_Epiphyseal_Plate.jpg?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail_unscaled",
    },
    {
        type: "detail",
        id: "fibrocartilage",
        title: "Fibrocartilage",
        image: "https://upload.wikimedia.org/wikipedia/commons/2/2e/Gray295.png?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail_unscaled",
    },
    {
        type: "detail",
        id: "elastic_cartilage",
        title: "Elastic Cartilage",
        image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4c/Connective_Tissue_Elastic_Cartilage_%2841855667361%29.jpg/960px-Connective_Tissue_Elastic_Cartilage_%2841855667361%29.jpg?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
    },
    {
        type: "detail",
        id: "compact_bone",
        title: "Compact Bone",
        image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c8/Left_femur_of_extinct_elephant%2C_Alaska%2C_Ice_Age_Wellcome_L0057714.jpg/960px-Left_femur_of_extinct_elephant%2C_Alaska%2C_Ice_Age_Wellcome_L0057714.jpg?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
    },
    {
        type: "detail",
        id: "spongy_bone",
        title: "Spongy Bone",
        image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/03/Bertazzo_S_-_SEM_deproteined_bone_-_wistar_rat_-_x10k.tif/lossy-page1-960px-Bertazzo_S_-_SEM_deproteined_bone_-_wistar_rat_-_x10k.tif.jpg?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
    },
    {
        type: "detail",
        id: "blood",
        title: "Blood",
        image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/50/Venous_and_arterial_blood.jpg/960px-Venous_and_arterial_blood.jpg?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
    },
    {
        type: "detail",
        id: "lymph",
        title: "Lymph",
        image: "https://upload.wikimedia.org/wikipedia/commons/1/19/Illu_lymph_capillary.png?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail_unscaled",
    },
]