import { Unit } from "../../../pages/api/studentPortal/units";

export const freemiumUnits: Unit[] = [
  {
    title: "Introduction",
    nodes: [
      {
        title: "Lesson",
        description: "Intro to Web Development",
        type: "lesson",
        completed: false,
        locked: false,
        link: "web/introduction",
      },
    ],
  },
  {
    title: "Github",
    nodes: [
      {
        title: "Lesson 1",
        description: "Deploying a Project on Github & Vercel",
        completed: false,
        locked: false,
        link: "web/React/github",
        type: "lesson",
      },
    ],
  },
  {
    title: "TailwindCSS",
    nodes: [
      {
        title: "Lesson 1",
        description: "TailwindCSS - Grid & Flexbox",
        completed: false,
        locked: false,
        link: "web/React/tailwindcss-gridflex",
        type: "lesson",
      },
      {
        title: "Lesson 2",
        description: "TailwindCSS - General Styling",
        completed: false,
        locked: false,
        link: "web/React/tailwindcss-colourstyling",
        type: "lesson",
      },
    ],
  },
  {
    title: "React",
    nodes: [
      {
        title: "Lesson 3",
        description: "Components",
        completed: false,
        locked: false,
        link: "web/React/components",
        type: "lesson",
      },
      {
        title: "Lesson 4",
        description: "Props",
        completed: false,
        locked: false,
        link: "web/React/props",
        type: "lesson",
      },
      {
        title: "Assignment 1",
        description: "Components and Props",
        completed: false,
        locked: false,
        link: "web/React/assignments/componentsAssignment",
        type: "lesson",
      },
      {
        title: "",
        description: "Enjoying the Skillify Experience?",
        completed: false,
        locked: false,
        link: "https://www.joinskillify.com/call",
        type: "lesson",
      },
      {
        title: "",
        description: "",
        completed: false,
        locked: true,
        link: "",
        type: "lesson",
      },
      {
        title: "",
        description: "",
        completed: false,
        locked: true,
        link: "",
        type: "lesson",
      },
      {
        title: "",
        description: "",
        completed: false,
        locked: true,
        link: "",
        type: "lesson",
      },
      {
        title: "",
        description: "",
        completed: false,
        locked: true,
        link: "",
        type: "lesson",
      },
      {
        title: "",
        description: "",
        completed: false,
        locked: true,
        link: "",
        type: "lesson",
      },
      {
        title: "",
        description: "",
        completed: false,
        locked: true,
        link: "",
        type: "lesson",
      },
    ],
  },
];
