export enum QuestionType {
  HORIZONTAL_EQUATION,
  VERTICAL_EQUATION,
  BINARY_WORD_PROBLEM,
  COMPARISON_WORD_PROBLEM,
  LONG_DIVISION_PROBLEM,
  TRUE_OR_FALSE_PROBLEM,
  FILL_IN_THE_BLANK_PROBLEM,
  PATTERN_COUNT_BLANKS_PROBLEM,
  VERTICAL_DIGITS_TO_NUM,
  NUM_TO_VERITCAL_DIGITS,
  WORD_TO_HORIZONTAL_DIGITS,
  ARRAY_QUESTION,
  MULTIPLICATION_EQUAL_GROUPS,
  MULTIPLE_CHOICE_WORD, // Addition Property with words as mc options
  MULTIPLE_CHOICE_SENTENCE, // Addition Property with numbers as mc options
  MULTIPLE_CHOICE, // Multiple choice answer to a binary question
}
