 //Jimi Interview Data
 export const JimiInterviewData: Offer[] = [
    {
      "Company": "BoomPop",
      "companyUrl": "https://www.boompop.com/",
      "Location": "Remote",
      "Role": "Senior Software Developer",
      "timeline": "2024",
      "timeSpentHours": 4,
      "Result": "Technical Screen",
      "Base": 185000,
      "askedTask": "Valid Anagrams, Lambda Functions (Flexibility vs Cold Start)",
      "industry": "Events"
    },
    {
      "Company": "Pepper",
      "companyUrl": "https://www.pepper.com/",
      "Location": "Remote",
      "Role": "Senior Software Developer",
      "timeline": "2024",
      "timeSpentHours": 2,
      "Result": "Recruiter Screen",
      "Base": 110000,
      "askedTask": "Braille to English Conversion Tool, Validate Sudoku, Snake Game",
      "industry": "Tech"
    },
    {
      "Company": "Shopify",
      "companyUrl": "https://www.shopify.com/",
      "Location": "Toronto",
      "Role": "Internship",
      "timeline": "2024",
      "timeSpentHours": 2,
      "Result": "OA",
      "Base": 80000,
      "askedTask": "Behavioral, ETLs",
      "industry": "E-Commerce"
    },
    {
      "Company": "Dawson and Partner",
      "companyUrl": "https://www.dawsonpartners.com/",
      "Location": "Remote",
      "Role": "Senior Software Developer",
      "timeline": "2024",
      "timeSpentHours": 2,
      "Result": "Technical Screen",
      "Base": 100000,
      "askedTask": "Interpolation and Calculating Slope, Closures, Hoisting, Async/Await Promises",
      "industry": "Consulting"
    },
    {
      "Company": "Vanta",
      "companyUrl": "https://www.vanta.com/",
      "Location": "Remote",
      "Role": "Senior Software Developer",
      "timeline": "2024",
      "timeSpentHours": 5,
      "Result": "Live Coding (2 Hours)",
      "Base": 220000,
      "askedTask": "Recursion, React App - List of Vendors and Categories, Data Transformation, Fetching and POST",
      "industry": "Security"
    },
    {
      "Company": "ResQ",
      "companyUrl": "https://www.resq.com/",
      "Location": "Remote",
      "Role": "Senior Software Developer",
      "timeline": "2024",
      "timeSpentHours": 3,
      "Result": "Project DeepDive",
      "Base": 120000,
      "askedTask": "7 Layers of Network Protocol",
      "industry": "Tech"
    },
    {
      "Company": "LotusFlare",
      "companyUrl": "https://www.lotusflare.com/",
      "Location": "Remote",
      "Role": "Senior Software Developer",
      "timeline": "2024",
      "timeSpentHours": 2,
      "Result": "Technical Screen",
      "Base": 150000,
      "askedTask": "Resume Dissection, Multi-Regions & High Availability, Optimizing APIs/SQL Queries/DB Indexing, Lowest Common Ancestor (LeetCode)",
      "industry": "Telecom"
    },
    {
      "Company": "SESO",
      "companyUrl": "https://www.sesolabor.com/",
      "Location": "Remote",
      "Role": "Senior Software Developer",
      "timeline": "2024",
      "timeSpentHours": 10,
      "Result": "System Design",
      "Base": 220000,
      "askedTask": "Draining Logs with a Heap, Notification System Design",
      "industry": "AgTech"
    },
    {
      "Company": "Ripple",
      "companyUrl": "https://www.ripple.com/",
      "Location": "Toronto",
      "Role": "Senior Software Developer",
      "timeline": "2024",
      "timeSpentHours": 3,
      "Result": "Engineering Manager Interview",
      "Base": 170000,
      "askedTask": "Talk about IC, Handling No Roadmap",
      "industry": "Finance"
    },
    {
      "Company": "Microsoft",
      "companyUrl": "https://www.microsoft.com/",
      "Location": "Remote",
      "Role": "Software Engineer II",
      "timeline": "2024",
      "timeSpentHours": 1,
      "Result": "Technical Screen",
      "Base": 170000,
      "askedTask": "Reverse a Linked List",
      "industry": "Tech"
    },
    {
      "Company": "Tanium",
      "companyUrl": "https://www.tanium.com/",
      "Location": "Remote",
      "Role": "Senior Software Developer",
      "timeline": "2024",
      "timeSpentHours": 8,
      "Result": "Completed!",
      "Base": 240000,
      "askedTask": "System Design - Monitoring System, Jump Game 4 (LeetCode)",
      "industry": "Security"
    },
    {
      "Company": "Affirm",
      "companyUrl": "https://www.affirm.com/",
      "Location": "Toronto",
      "Role": "Senior Software Developer",
      "timeline": "2024",
      "timeSpentHours": 2,
      "Result": "Technical Screen 2",
      "Base": 180000,
      "askedTask": "Anagrams and Grouped Anagrams",
      "industry": "Finance"
    },
    {
      "Company": "TikTok",
      "companyUrl": "https://www.tiktok.com/",
      "Location": "Toronto",
      "Role": "Senior Software Developer",
      "timeline": "2024",
      "timeSpentHours": 1,
      "Result": "Technical Screen",
      "Base": 200000,
      "askedTask": "Random LeetCode Question, React - Nested JSON",
      "industry": "Social Media"
    }
  ];
