import { Offer } from "../../../../components/resources/jobTracker/JobTrackerComponent";

 //Jimi Interview Data
 export const JimiInterviewData: Offer[] = [
    {
      "Company": "BoomPop",
      "companyUrl": "https://www.boompop.com/",
      "Location": "Remote",
      "Role": "Senior Software Developer",
      "timeline": "Jun 2024",
      "timeSpentHours": 4,
      "Result": "Failed Technical Screen",
      "Base": 185000,
      "askedTask": "Valid Anagrams, Lambda Functions (Flexibility vs Cold Start)",
      "industry": "Events"
    },
    {
      "Company": "Pepper",
      "companyUrl": "https://www.pepper.com/",
      "Location": "Remote",
      "Role": "Senior Software Developer",
      "timeline": "Jun 2024",
      "timeSpentHours": 2,
      "Result": "Failed Recruiter Screen",
      "Base": 110000,
      "askedTask": "Braille to English Conversion Tool, Validate Sudoku, Snake Game",
      "industry": "Tech"
    },
    {
      "Company": "Shopify",
      "companyUrl": "https://www.shopify.com/",
      "Location": "Toronto",
      "Role": "Internship",
      "timeline": "Aug 2024",
      "timeSpentHours": 2,
      "Result": "Passed OA",
      "Base": 80000,
      "askedTask": "Behavioral, ETLs",
      "industry": "E-Commerce"
    },
    {
      "Company": "Dawson and Partner",
      "companyUrl": "https://www.dawsonpartners.com/",
      "Location": "Remote",
      "Role": "Senior Software Developer",
      "timeline": "August 2024",
      "timeSpentHours": 2,
      "Result": "Failed Technical Screen",
      "Base": 100000,
      "askedTask": "Interpolation and Calculating Slope, Closures, Hoisting, Async/Await Promises",
      "industry": "Consulting"
    },
    {
      "Company": "Vanta",
      "companyUrl": "https://www.vanta.com/",
      "Location": "Remote",
      "Role": "Senior Software Developer",
      "timeline": "August 2024",
      "timeSpentHours": 5,
      "Result": "Failed Live Coding",
      "Base": 220000,
      "askedTask": "Recursion, React App - List of Vendors and Categories, Data Transformation, Fetching and POST",
      "industry": "Security"
    },
    {
      "Company": "ResQ",
      "companyUrl": "https://www.resq.com/",
      "Location": "Remote",
      "Role": "Senior Software Developer",
      "timeline": "Mar 2024",
      "timeSpentHours": 3,
      "Result": "Failed Project DeepDive",
      "Base": 120000,
      "askedTask": "7 Layers of Network Protocol",
      "industry": "Tech"
    },
    {
      "Company": "LotusFlare",
      "companyUrl": "https://www.lotusflare.com/",
      "Location": "Remote",
      "Role": "Senior Software Developer",
      "timeline": "Sept 2024",
      "timeSpentHours": 2,
      "Result": "Failed Technical Screen",
      "Base": 150000,
      "askedTask": "Resume Dissection, Multi-Regions & High Availability, Optimizing APIs/SQL Queries/DB Indexing, Lowest Common Ancestor (LeetCode)",
      "industry": "Telecom"
    },
    {
      "Company": "SESO",
      "companyUrl": "https://www.sesolabor.com/",
      "Location": "Remote",
      "Role": "Senior Software Developer",
      "timeline": "Sept 2024",
      "timeSpentHours": 10,
      "Result": "Failed System Design",
      "Base": 220000,
      "askedTask": "Draining Logs with a Heap, Notification System Design",
      "industry": "AgTech"
    },
    {
      "Company": "Ripple",
      "companyUrl": "https://www.ripple.com/",
      "Location": "Toronto",
      "Role": "Senior Software Developer",
      "timeline": "Oct 2024",
      "timeSpentHours": 3,
      "Result": "Failed Engineering Manager Interview",
      "Base": 170000,
      "askedTask": "Talk about IC, Handling No Roadmap",
      "industry": "Finance"
    },
    {
      "Company": "Microsoft",
      "companyUrl": "https://www.microsoft.com/",
      "Location": "Remote",
      "Role": "Software Engineer II",
      "timeline": "March 2024",
      "timeSpentHours": 1,
      "Result": "Passed Technical Screen",
      "Base": 170000,
      "askedTask": "Reverse a Linked List",
      "industry": "Tech"
    },
    {
      "Company": "Tanium",
      "companyUrl": "https://www.tanium.com/",
      "Location": "Remote",
      "Role": "Senior Software Developer",
      "timeline": "2024",
      "timeSpentHours": 8,
      "Result": "Job Offer!",
      "Base": 240000,
      "askedTask": "System Design - Monitoring System, Jump Game (LeetCode)",
      "industry": "Security"
    },
    {
      "Company": "Affirm",
      "companyUrl": "https://www.affirm.com/",
      "Location": "Toronto",
      "Role": "Senior Software Developer",
      "timeline": "Aug 2024",
      "timeSpentHours": 2,
      "Result": "Failed Technical Screen 2",
      "Base": 180000,
      "askedTask": "Anagrams and Grouped Anagrams",
      "industry": "Finance"
    },
    {
      "Company": "TikTok",
      "companyUrl": "https://www.tiktok.com/",
      "Location": "Toronto",
      "Role": "Senior Software Developer",
      "timeline": "Nov 2024",
      "timeSpentHours": 1,
      "Result": "Failed Technical Screen",
      "Base": 200000,
      "askedTask": "Random LeetCode Question, React - Nested JSON",
      "industry": "Social Media"
    },
    {
      "Company": "PostScript",
      "companyUrl": "https://www.postscript.io/",
      "Location": "Toronto",
      "Role": "Senior Engineer",
      "timeline": "Oct 2024",
      "timeSpentHours": 4,
      "Result": "Failed Technical Screen",
      "Base": 240000,
      "askedTask": "Take Home Assessment (2-3 hours)",
      "industry": "Marketing"
    },
    {
      "Company": "First Principles",
      "companyUrl": "https://www.firstprinciples.com/",
      "Location": "Toronto",
      "Role": "Founding Engineer",
      "timeline": "Ongoing",
      "timeSpentHours": 4,
      "Result": "Failed Technical Screen",
      "Base": 170000,
      "askedTask": "Leetcode (1 hour)",
      "industry": "Consulting"
    },
    {
      "Company": "EvenUp",
      "companyUrl": "https://www.evenup.com/",
      "Location": "Toronto",
      "Role": "Senior Engineer",
      "timeline": "Nov 2024",
      "timeSpentHours": 4,
      "Result": "Failed Engineering Manager Screen",
      "Base": 170000,
      "askedTask": "General Technical Questions, Project DeepDive",
      "industry": "Legal Tech"
    },
    {
      "Company": "Cresta",
      "companyUrl": "https://www.cresta.com/",
      "Location": "Toronto",
      "Role": "Senior Software Developer",
      "timeline": "Ongoing",
      "timeSpentHours": 1,
      "Result": "Ongoing",
      "Base": 150000,
      "askedTask": "Leetcode (1 hour)",
      "industry": "Artificial Intelligence"
    },
    {
      "Company": "Develo",
      "companyUrl": "https://www.develo.com/",
      "Location": "Toronto",
      "Role": "Senior Full-Stack Engineer",
      "timeline": "Oct 2024",
      "timeSpentHours": 1,
      "Result": "Failed Recruiter Screen",
      "Base": 100000,
      "askedTask": "General Behavioural Questions",
      "industry": "Software Development"
    },
    {
      "Company": "Float",
      "companyUrl": "https://www.float.com/",
      "Location": "Toronto",
      "Role": "Senior Full-Stack Engineer",
      "timeline": "Oct 2024",
      "timeSpentHours": 2,
      "Result": "Failed Engineering Manager Screen",
      "Base": 100000,
      "askedTask": "General Technical Questions",
      "industry": "Financial Services"
    },
    {
      "Company": "CommerceBear",
      "companyUrl": "https://www.commercebear.com/",
      "Location": "Toronto",
      "Role": "Senior Full-Stack Engineer",
      "timeline": "Ongoing",
      "timeSpentHours": 2,
      "Result": "Ongoing",
      "Base": 100000,
      "askedTask": "Project DeepDive (Need to schedule)",
      "industry": "E-Commerce"
    },
    {
      "Company": "ToolBX",
      "companyUrl": "https://www.toolbx.com/",
      "Location": "Toronto",
      "Role": "Senior Full-Stack Engineer",
      "timeline": "Dec 2024",
      "timeSpentHours": 1,
      "Result": "Failed Technical Screen",
      "Base": 135000,
      "askedTask": "Online Assessment (1 hour)",
      "industry": "Construction Tech"
    },
    {
      "Company": "Laurel",
      "companyUrl": "https://www.laurel.com/",
      "Location": "Toronto",
      "Role": "Senior Full-Stack Engineer",
      "timeline": "Jan 2025",
      "timeSpentHours": 3,
      "Result": "Failed Technical Screen",
      "Base": 150000,
      "askedTask": "What is CQRS?\nWhat is event driven architecture?",
      "industry": "Software Development"
    },
    {
      "Company": "PolicyMe",
      "companyUrl": "https://www.policyme.com/",
      "Location": "Toronto",
      "Role": "Senior Full-Stack Engineer",
      "timeline": "Jan 2025",
      "timeSpentHours": 4,
      "Result": "Failed Technical Screen",
      "Base": 120000,
      "askedTask": "Take home Assessment (2-3 Hour Limit)",
      "industry": "Insurance"
    }
  ];